name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: "pip"
        cache-dependency-path: "pyproject.toml"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[test]'

    - name: Lint
      run: |
        make lint

    - name: Run tests
      run: |
        make coverage_report

    - name: Coveralls coverage report
      uses: coverallsapp/github-action@v2

    - name: Qlty coverage report
      if: matrix.os == 'ubuntu-latest'
      uses: qltysh/qlty-action/coverage@v1
      with:
        token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        files: coverage.info